name: backend
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - fastapi
    - uvicorn
    - sqlalchemy
    - psycopg2-binary
    - motor
    - pydantic
    - pydantic-settings
    - python-jose[cryptography]
    - passlib[bcrypt]
    - python-multipart
    - httpx
    - beautifulsoup4
